version: "3.7"
services:
  master:
    image: locustio/locust:2.15.1
    ports:
      - target: 8089
        published: 8089
        protocol: tcp
        mode: ingress
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    image: locustio/locust:2.15.1
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  nginx:
    image: nginx:1.23.3
    ports:
      - target: 80
        published: 8090
        protocol: tcp
        mode: ingress